### ISSUE TITLE
List Which Dependencies are Required to Build

### ISSUE THREAD

**Issue by 4tuw2tuv0** [nwg-piotr/nwg-icon-picker#2]
`nwg-panel` lists out exactly what's required at https://github.com/nwg-piotr/nwg-panel/wiki/Installation.

Likewise would be helpful for the icon picker for anyone packaging the project for other repo.s.

**Comment by 4tuw2tuv0** [comment]
Awesome; thanks! 'Should be able to package this for Guix, now.

**Comment by nwg-piotr** [comment]
Any time. You can always take a look at AUR to check dependencies. https://aur.archlinux.org/packages?K=nwg&SeB=m
